### ISSUE TITLE
To trigger the M112 from a closed switch.

### ISSUE THREAD

**Issue by Hoseasack** [Mechazawa/Emergency_stop_simplified#2]
In a future release, there should be a setting for if you have a normally open switch.

**Comment by crysxd** [comment]
Simple checkbox to invert the button state would be amazing!

**Comment by crysxd** [comment]
I forked this repo and added the functionality: https://github.com/crysxd/Emergency_stop_simplified

You can download the repository as zip, uninstall the old plugin and install the zip. I also opened a pull request, so hopefully the functionality is integrated soon
<img width="1312" alt="Screen Shot 2020-05-23 at 12 02 30" src="https://user-images.githubusercontent.com/5859228/82727854-52e2d100-9ced-11ea-8e9c-8ea936c32b96.png">
